"""
Test report generator.

Outputs a markdown report with:
- Summary (pass/fail counts, duration)
- Each step with before/after screenshots and verification results
- Embedded base64 images (self-contained, no external files needed)
"""

from __future__ import annotations

import time
from pathlib import Path

from screen_agent.testing.session import TestSession, TestStep, StepStatus


class TestReporter:
    """Generates markdown test reports from completed sessions."""

    @staticmethod
    def generate_markdown(session: TestSession, include_screenshots: bool = True) -> str:
        """Generate a self-contained markdown test report."""
        lines: list[str] = []

        # Header
        status_emoji = "✅" if session.all_passed else "❌"
        lines.append(f"# {status_emoji} Test Report: {session.name}")
        lines.append("")

        if session.description:
            lines.append(f"> {session.description}")
            lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| **Result** | {'PASSED' if session.all_passed else 'FAILED'} |")
        lines.append(f"| **Steps** | {session.passed_count}/{len(session.steps)} passed |")
        lines.append(f"| **Duration** | {session.total_duration_ms:.0f}ms |")
        lines.append(f"| **Timestamp** | {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(session.started_at))} |")
        lines.append("")

        # Steps
        lines.append("## Steps")
        lines.append("")

        for step in session.steps:
            lines.extend(TestReporter._render_step(step, include_screenshots))

        # Footer
        lines.append("---")
        lines.append("*Generated by screen-agent test runner*")

        return "\n".join(lines)

    @staticmethod
    def _render_step(step: TestStep, include_screenshots: bool) -> list[str]:
        lines: list[str] = []

        # Step header with status
        status_map = {
            StepStatus.PASSED: "✅",
            StepStatus.FAILED: "❌",
            StepStatus.ERROR: "⚠️",
            StepStatus.SKIPPED: "⏭️",
            StepStatus.RUNNING: "🔄",
            StepStatus.PENDING: "⏳",
        }
        emoji = status_map.get(step.status, "❓")

        lines.append(f"### Step {step.index}: {emoji} {step.description}")
        lines.append("")

        # Action
        if step.action:
            lines.append(f"**Action:** {step.action}")
            lines.append("")

        # Duration
        if step.duration_ms:
            lines.append(f"**Duration:** {step.duration_ms:.0f}ms")
            lines.append("")

        # Screenshots side by side
        if include_screenshots:
            has_before = step.before_screenshot is not None
            has_after = step.after_screenshot is not None

            if has_before or has_after:
                lines.append("| Before | After |")
                lines.append("|--------|-------|")

                before_img = ""
                after_img = ""
                if has_before:
                    before_img = f"![before](data:{step.before_screenshot.mime_type};base64,{step.before_screenshot.image_base64})"
                if has_after:
                    after_img = f"![after](data:{step.after_screenshot.mime_type};base64,{step.after_screenshot.image_base64})"

                lines.append(f"| {before_img} | {after_img} |")
                lines.append("")

        # Verification
        if step.verification:
            v = step.verification
            if v.passed:
                lines.append(f"**Verification ({v.method}):** ✅ PASSED")
            else:
                lines.append(f"**Verification ({v.method}):** ❌ FAILED")

            if v.expected:
                lines.append(f"- Expected: `{v.expected}`")
            if v.actual:
                lines.append(f"- Actual: `{v.actual}`")
            if v.confidence < 1.0:
                lines.append(f"- Confidence: {v.confidence:.1%}")
            lines.append("")

        # Error
        if step.error_message:
            lines.append(f"**Error:** {step.error_message}")
            lines.append("")

        lines.append("---")
        lines.append("")

        return lines

    @staticmethod
    def save(session: TestSession, output_dir: str = ".", include_screenshots: bool = True) -> str:
        """Save report to file. Returns the file path."""
        report = TestReporter.generate_markdown(session, include_screenshots)

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        timestamp = time.strftime("%Y%m%d_%H%M%S", time.localtime(session.started_at))
        safe_name = session.name.replace(" ", "_").replace("/", "_")[:50]
        filename = f"test_report_{safe_name}_{timestamp}.md"

        filepath = output_path / filename
        filepath.write_text(report, encoding="utf-8")

        return str(filepath)
